name: Ordenar archivos

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Run Script
        run: python .ordenar_archivos.py

      - name: commit  and push Changes auto
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Ordenar_archivos
          commit_user_name: Esteban Sanchez
          commit_user_emai: ing.inocencio@hotmail.com
          commit_author: I.esteban
