name: Ordenar archivos

on:
  schedule:
    # Run at 12 AM UTC every day
    cron: "00 00 * * *"

jobs:
  ordenar-archivos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute Python script
        run: python ordenar_archivos.py

    
